databases:
  - name: "Bibleball DB"
    plan: free
    databaseName: bibleball_db
    user: bibleball_user

services:
  - type: web
    plan: free
    name: bibleball
    env: docker
    repo: https://github.com/nicoavn/bibleball
    branch: main
    runtime: python
    dockerfilePath: backend/Dockerfile_render
    buildCommand: './build.sh'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: "Bibleball DB"
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: "False"
