FROM python:3.12

RUN mkdir /backend
WORKDIR /backend

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY requirements.txt /backend

RUN pip install --upgrade pip
RUN python -m pip install --no-cache-dir -r /backend/requirements.txt

COPY . /backend/

# Expose the Django port
EXPOSE 10000

# Start the app
CMD ["gunicorn", "core.wsgi:application", "--bind", "0.0.0.0:10000"]
