# Generated by Django 5.1.5 on 2025-01-26 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_total_innings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameevent',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='member',
            name='order',
        ),
        migrations.AddField(
            model_name='teammember',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='nickname',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(blank=True, choices=[('P', 'Pitcher'), ('1B', 'First Base'), ('2B', 'Second Base'), ('3B', 'Third Base'), ('C', 'Catcher'), ('LF', 'Left Field'), ('CF', 'Center Field'), ('RF', 'Right Field'), ('DH', 'Designated Hitter')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='questionpack',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_packs', to='game.pack'),
        ),
        migrations.AlterField(
            model_name='questionpack',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_packs', to='game.question'),
        ),
    ]
