# Generated by Django 5.1.5 on 2025-01-26 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_gameevent_options_alter_teammember_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inning',
            options={'ordering': ['number']},
        ),
    ]
