# Generated by Django 5.1.5 on 2025-02-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0006_gameevent_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                related_name="teams", through="game.TeamMember", to="game.member"
            ),
        ),
    ]
