# Generated by Django 5.1.5 on 2025-04-17 00:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0007_team_members"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="questionpack",
            unique_together={("pack", "question")},
        ),
    ]
