# Generated by Django 5.1.5 on 2025-05-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0010_remove_member_position_teammember_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="short_code",
            field=models.CharField(blank=True, default="", max_length=10, unique=True),
        ),
    ]
