# Generated by Django 5.1.5 on 2025-05-28 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0011_game_short_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="short_code",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=10, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="game",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="game.game"
            ),
        ),
    ]
